# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTimkiemsplzd1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_timkiemsplzd1(self):
    self.driver.get("https://www.lazada.vn/?dsource=share&laz_share_info=1093623010_1_9300_200395408016_1093623010_null&laz_token=44977719e463eb91cd6d76ef6aa46cf0&trafficFrom=17449020_303586&laz_trackid=2:mm_228101231_71453284_2030303371:clkgislgd1ie7qbhg4jgrg&mkttid=clkgislgd1ie7qbhg4jgrg#?")
    self.driver.set_window_size(1051, 798)
    self.driver.find_element(By.ID, "q").click()
    self.driver.find_element(By.ID, "q").send_keys("iphone 14 plus")
    self.driver.find_element(By.ID, "q").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".Bm3ON:nth-child(1) .buTCk").click()
    self.driver.find_element(By.CSS_SELECTOR, ".Bm3ON:nth-child(1) .RfADt").click()
    self.driver.find_element(By.CSS_SELECTOR, ".Bm3ON:nth-child(1) .RfADt").click()
    assert self.driver.find_element(By.LINK_TEXT, "iPhone 14 Plus - Hàng Chính Hãng VN/A").text == "iPhone 14 Plus - Hàng Chính Hãng VN/A"
  
 